### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by toplisek** [felixhagspiel/customInputs#1]
.fh-switch > [type="checkbox"]:checked + label + .fh-switch-knob, .fh-switch > [type="checkbox"]:not(:checked) + label + .fh-switch-knob    

I kindly ask you to check this line.
There is validation error and all other part is without an error:
Property pointer-events doesn't exist : none

**Comment by toplisek** [comment]
Can you reply?

**Comment by felixhagspiel** [comment]
@toplisek hey, sorry for late reply. What exactly do you mean by "validation error"? In your IDE?

**Comment by felixhagspiel** [comment]
as far as I know, `pointer-events: none;` is valid. Chrome dev tools also give it as suggestion:
![](http://content.screencast.com/users/felixhagspiel/folders/Jing/media/3ac26611-58cb-46e9-bd8c-56855d490229/00000132.png)

I think you have to supress it in your IDE.
